from abc import ABC, abstractmethod

from core.utils.compatible_mixins import CompatibleMarkupLanguagesMixin, IdentifiableMixin


class Compiler(IdentifiableMixin, CompatibleMarkupLanguagesMixin, ABC):

     @abstractmethod
     def compile(self, payload: str, output_path: str, dump_markuplang_file: bool = True, markuplang_file_path: str | None = None):
         """
         :param payload:
         :param output_path: path in which output will be dumped
         :param dump_markuplang_file: if True, dump diagram markup language representation into file
         :param markuplang_file_path: considered only if markuplang dump is True; if None dump with autogenerated file name, else it will use specified one
         """